/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::EnumMeasureIdentifier
  File Path:     ../../Core/Interface/Base/EnumMeasureIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_EnumMeasureIdentifier_H
#define Core_Interface_Base_EnumMeasureIdentifier_H

//## class EnumMeasureIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class EnumMeasureIdentifier
    // Type safe Identifier for EnumMeasures.
    typedef TypedIdentifier<Identifier::EnumMeasureType> EnumMeasureIdentifier;
    
    //## package Core::Interface::Base
    
    //## class EnumMeasureIdentifier
}

#endif
