/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::EnumSettingIdentifier
  File Path:     ../../Core/Interface/Base/EnumSettingIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_EnumSettingIdentifier_H
#define Core_Interface_Base_EnumSettingIdentifier_H

//## class EnumSettingIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class EnumSettingIdentifier
    // Type safe Identifier for EnumSettings.
    typedef TypedIdentifier<Identifier::EnumSettingType> EnumSettingIdentifier;
    
    //## package Core::Interface::Base
    
    //## class EnumSettingIdentifier
}

#endif
