/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::IntervalIdentifier
  File Path:     ../../Core/Interface/Base/IntervalIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_IntervalIdentifier_H
#define Core_Interface_Base_IntervalIdentifier_H

//## class IntervalIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class IntervalIdentifier
    typedef TypedIdentifier<Identifier::IntervalType> IntervalIdentifier;
    
    //## package Core::Interface::Base
    
    //## class IntervalIdentifier
}

#endif
