/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::NumericalMeasureIdentifier
  File Path:     ../../Core/Interface/Base/NumericalMeasureIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_NumericalMeasureIdentifier_H
#define Core_Interface_Base_NumericalMeasureIdentifier_H

//## class NumericalMeasureIdentifier
#include "TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class NumericalMeasureIdentifier
    // Type safe Identifier for NumericalMeasures.
    typedef TypedIdentifier<Identifier::NumericalMeasureType> NumericalMeasureIdentifier;
    
    //## package Core::Interface::Base
    
    //## class NumericalMeasureIdentifier
}

#endif
