/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::NumericalSettingIdentifier
  File Path:     ../../Core/Interface/Base/NumericalSettingIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_NumericalSettingIdentifier_H
#define Core_Interface_Base_NumericalSettingIdentifier_H

//## class NumericalSettingIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class NumericalSettingIdentifier
    // Type safe Identifier for NumericalSettings.
    typedef TypedIdentifier<Identifier::NumericalSettingType> NumericalSettingIdentifier;
    
    //## package Core::Interface::Base
    
    //## class NumericalSettingIdentifier
}

#endif
