/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::RawDataIdentifier
  File Path:     ../../Core/Interface/Base/RawDataIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_RawDataIdentifier_H
#define Core_Interface_Base_RawDataIdentifier_H

//## class RawDataIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class RawDataIdentifier
    typedef TypedIdentifier<Identifier::RawDataType> RawDataIdentifier;
    
    //## package Core::Interface::Base
    
    //## class RawDataIdentifier
}

#endif
