/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::SharedObjectIdentifier
  File Path:     ../../Core/Interface/Base/SharedObjectIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_SharedObjectIdentifier_H
#define Core_Interface_Base_SharedObjectIdentifier_H

//## class SharedObjectIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class SharedObjectIdentifier
    // Type safe Identifier for shared data (e.g. shared memory identifiers)
    typedef TypedIdentifier<Identifier::SharedObject> SharedObjectIdentifier;
    
    //## package Core::Interface::Base
    
    //## class SharedObjectIdentifier
}

#endif
