/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::TimestampIdentifier
  File Path:     ../../Core/Interface/Base/TimestampIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_TimestampIdentifier_H
#define Core_Interface_Base_TimestampIdentifier_H

//## class TimestampIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class TimestampIdentifier
    typedef TypedIdentifier<Identifier::TimestampType> TimestampIdentifier;
    
    //## package Core::Interface::Base
    
    //## class TimestampIdentifier
}

#endif
