/********************************************************************
  Copyright Draegerwerk AG & Co. KGaA
  Generated by Rhapsody 7.5.1 
  Component:     Core 
  Configuration: ClearCase
  Model Element: Core::WaveformIdentifier
  File Path:     ../../Core/Interface/Base/WaveformIdentifier.h
*********************************************************************/

#ifndef Core_Interface_Base_WaveformIdentifier_H
#define Core_Interface_Base_WaveformIdentifier_H

//## class WaveformIdentifier
#include "Core/Interface/Base/TypedIdentifier.h"
namespace Core {
    //## package Core::Interface::Base
    
    //## class WaveformIdentifier
    // Type safe Identifier for Waveforms.
    typedef TypedIdentifier<Identifier::WaveformType> WaveformIdentifier;
    
    //## package Core::Interface::Base
    
    //## class WaveformIdentifier
}

#endif
